export {default as Notice} from './Notice'
export {default as Community} from './Community'
export {default as Contacts} from './Contacts'
export {default as Events} from './Events'
export {default as Main} from './Main'
