import {default as Community} from './Community'
import {default as Contacts} from './Contacts'
import {default as Events} from './Events'
import {default as Home} from './Home'
import {default as Main} from './Main'